version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.minidev:json-smart
    versions:
    - 2.4.2
    - 2.4.4
    - 2.4.5
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
  - dependency-name: com.nimbusds:nimbus-jose-jwt
    versions:
    - 9.4.2
    - "9.5"
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
  - dependency-name: com.forgerock.openbanking:forgerock-openbanking-starter-parent
    versions:
    - 1.0.86
  - dependency-name: org.bouncycastle:bcpkix-jdk15on
    versions:
    - "1.68"
  - dependency-name: junit:junit
    versions:
    - 4.13.1
